sudo: required
language: go
go:
  - "1.13.x"
services:
  - docker

addons:
  apt:
    packages:
      - rpm

notifications:
  email: false

env:
  global:
    - SKEEMA_TEST_IMAGES="mysql:5.6,mysql:5.7"
    - GO111MODULE=on
    - GOFLAGS="-mod=vendor"

install: true

before_install:
  - go install golang.org/x/lint/golint
  - go install github.com/mattn/goveralls

script:
  - go test -v -p 1 -coverprofile=coverage.out -coverpkg=./... ./...
  - goveralls -v -service=travis-ci -coverprofile=coverage.out
  - go vet ./...
  - test -z "$(gofmt -s -d {.,fs,workspace,util,applier,linter,dumper}/*.go 2>&1)"
  - go list -f '{{.Dir}}' ./... | xargs golint -set_exit_status

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
